<?php

namespace App\Http\Facades;
use Illuminate\Support\Facades\Facade;

class  Testfas extends Facade
{
    protected static function getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
            return "Testfas";
    }

}

?>